### PR TITLE
Update DashboardPage to be responsive.

### PR DESCRIPTION
**Pull request by asimbera**

### CODE REVIEW

**Comment by thatsuman** [comment]
Can't navigate through different pages in dashboard in mobile.

**Comment by thatsuman** [comment]
Puro chumu!
Ready to merge 🥳

**Comment by asimbera** [comment]
> Puro chumu!
> Ready to merge 🥳  

Review ta kor. `Mark as Reviewed` ota kor.

**Comment by thatsuman** [comment]
> > Puro chumu!
> > Ready to merge partying_face
> 
> Review ta kor. `Mark as Reviewed` ota kor.

https://tenor.com/bpweT.gif

**Review by thatsuman — APPROVED** [review]
Good work comrade :)

**Pull request merged**
